"""TRIM: Threshold–Rationale Interpretive Modelling.

TRIM validates and compares human-created annotations.
"""

from trim.io import (
    annotations_to_dataframe,
    build_annotation_graph,
    load_annotations,
    load_csv,
    load_json,
    save_annotations,
)
from trim.compare import (
    broad_family_table,
    compare_case_pair,
    contested_cases_table,
    find_contested_cases,
    find_same_broad_family_different_signature,
    find_same_cue_different_function,
    find_same_function_different_signature,
    group_by_function,
    same_cue_table,
    same_function_table,
    signature_string,
)
from trim.graph import (
    build_case_graph,
    build_corpus_graph,
    export_graphml,
    export_json_graph,
    graph_summary,
)
from trim.intercoder import (
    apply_disagreement_categories,
    cohen_kappa_if_two_coders,
    compatible_single_compound_value,
    compound_value_metrics,
    contested_disagreement_report,
    disagreement_table,
    pairwise_agreement,
    pairwise_compound_agreement,
    pairwise_segment_agreement,
    percent_agreement,
    primary_context_segment_overlap,
    pivot_coder_annotations,
    segment_set_metrics,
    stratified_pairwise_agreement,
)
from trim.reports import generate_demo_report, write_markdown_table
from trim.schema import (
    ANNOTATION_FIELDS,
    AnchorNode,
    EvidenceNode,
    FunctionNode,
    ThresholdRationaleEdge,
    TrimAnnotation,
)
from trim.signature import (
    FrictionSignature,
    compare_annotations,
    parse_signature,
    signature_from_annotation,
)
from trim.validator import (
    ValidationIssue,
    ValidationReport,
    validate_annotation,
    validate_annotations,
    validate_retest_manifest,
    validate_shared_context_registry,
    validate_source_packet_segment_coverage,
)

__all__ = [
    "ANNOTATION_FIELDS",
    "AnchorNode",
    "EvidenceNode",
    "FrictionSignature",
    "FunctionNode",
    "ThresholdRationaleEdge",
    "TrimAnnotation",
    "ValidationIssue",
    "ValidationReport",
    "annotations_to_dataframe",
    "apply_disagreement_categories",
    "broad_family_table",
    "build_annotation_graph",
    "build_case_graph",
    "build_corpus_graph",
    "compare_annotations",
    "compare_case_pair",
    "compatible_single_compound_value",
    "compound_value_metrics",
    "contested_cases_table",
    "cohen_kappa_if_two_coders",
    "contested_disagreement_report",
    "disagreement_table",
    "export_graphml",
    "export_json_graph",
    "find_contested_cases",
    "find_same_broad_family_different_signature",
    "find_same_cue_different_function",
    "find_same_function_different_signature",
    "generate_demo_report",
    "graph_summary",
    "group_by_function",
    "load_annotations",
    "load_csv",
    "load_json",
    "pairwise_agreement",
    "pairwise_compound_agreement",
    "pairwise_segment_agreement",
    "percent_agreement",
    "primary_context_segment_overlap",
    "parse_signature",
    "pivot_coder_annotations",
    "save_annotations",
    "same_cue_table",
    "same_function_table",
    "segment_set_metrics",
    "signature_from_annotation",
    "signature_string",
    "stratified_pairwise_agreement",
    "validate_annotation",
    "validate_annotations",
    "validate_retest_manifest",
    "validate_shared_context_registry",
    "validate_source_packet_segment_coverage",
    "write_markdown_table",
]
